spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunwu?useSSL=false
    username: root
    password: 123456

   # Thymeleaf
  thymeleaf:
    cache: false

  # multipart config
  http:
    multipart:
      enabled: true
      location: E:\Project\Java\xunwu\temp
      file-size-threshold: 5MB
      max-request-size: 20MB

  # ES
  data:
    elasticsearch:
      cluster-name: xunwu
