spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: root
      password: 123456
logging:
  level:
    org:
      hibernate:
        SQL: debug
