spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunwu?useSSL=false
    username: root
    password: 123456

   # Thymeleaf
  thymeleaf:
    cache: false
