spring:
  profiles:
    active: dev

  # jpa config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  # security config
#  security:
#    user:
#      name: root
#      password: 123456

  # Thymeleaf config
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  # redis config
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      min-idle: 1
    timeout: 3000

  # session会话存储类型
  session:
    store-type: redis

# 不要springboot生成whitelabel页面
server:
  error:
    whitelabel:
      enabled: false

# log config
logging:
  level:
    org:
      hibernate:
        SQL: debug

# qiniu
qiniu:
  AccessKey: wQKZ54zYCI0bVXfH9YajI8_EQGpvkRdtXcG_H7AB
  SecretKey: qx52pYjI3vbYmZTxh-a1AQdswnc8Q8cZrThBZYkB
  Bucket: jang1995
  cdn:
    prefix: http://q3f7ttmqr.bkt.clouddn.com/
